"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Components/Navbar/Navbar'
import { QueryClientProvider,QueryClient } from 'react-query'
import { ReactQueryDevtools} from 'react-query/devtools'

const inter = Inter({ subsets: ['latin'] })
const queryClient = new QueryClient()
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
        <Navbar/>
        {children}
         <ReactQueryDevtools initialIsOpen={false} position="bottom-right" />
        </QueryClientProvider>
       
        </body>
    </html>
  )
}
